CC = g++

bufia:
	$(CC) -O3 -o bufia bufia_init_utils.cc bufia_algorithm_utils.cc factor.cc bufia.cc

sandbox:
	$(CC) -o sandbox factor.cc bufia_algorithm_utils.cc sandbox.cc

clean:
	rm -f *.o bufia sandbox

